#!/usr/bin/env bash
# Bash script that will display information about subdomains.
function display_info()
{
	command=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tail -1 | sed "s/\t/ /g");
	record=$(echo "$command" | cut -d " " -f4);
	ip=$(echo "$command" | cut -d " " -f5);
	echo "The subdomain $2 is a $record record and points to $ip";
}
if [ "$#" == 1 ]
then
  display_info "$1" "www"
  display_info "$1" "lb-01"
  display_info "$1" "web-01"
  display_info "$1" "web-02"
elif [ "$#" == 2 ]
then
  display_info "$1" "$2"
fi
