#!/usr/bin/env bash
# Bash script that install and configure HAproxy on lb-01 server
apt-get -y update && apt-get upgrade -y
apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.5
apt-get -y update && apt-get install haproxy -y
sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy
echo -e "frontend http-in
    bind *:80
    mode http
    default_backend servers

backend servers
    balance roundrobin
    server 388479-web-01 54.160.103.40:80 check
    server 388479-web-02 52.91.148.127:80 check
" >> /etc/haproxy/haproxy.cfg
service haproxy restart