#!/usr/bin/env bash
# Bash script to do the same task before but with only 5 lines
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
kill "$(pgrep 'nginx' | head -1)"
