#!/usr/bin/env bash
#Bash script to deal with some signals and create some files.
echo $$ > /var/run/myscript.pid;
iter=1;
trap 'echo "I hate the kill command" && sudo rm /var/run/myscript.pid && exit' SIGTERM;
trap 'echo "Y U no love me?!" && exit' SIGINT;
trap 'sudo rm /var/run/myscript.pid && exit' SIGQUIT;
while [ $iter -eq 1 ]
do
	echo "To infinity and beyond";
	sleep 2;
done
