#!/usr/bin/env bash
#Script to check if a number is Fizz, Buzz, FizzBuzz or nothing
number=1;
while [ $number -le 100 ]
do
	if [ $((number % 5)) -eq 0 ] && [ $((number % 3)) -eq 0 ]
	then
		echo "FizzBuzz";
	elif [ $((number % 5)) -eq 0 ]
	then
		echo "Buzz";
	elif [ $((number % 3)) -eq 0 ]
	then
		echo "Fizz";
	else
		echo $number;
	fi
	((number++));
done
