#!/usr/bin/env bash
#Script to display the contents of the /etc/passwd file.
file="/etc/passwd";
while read -r line
do
	username=$(echo "$line" | cut -d ":" -f1);
	user_id=$(echo "$line" | cut -d ":" -f3);
	path=$(echo "$line" | cut -d ":" -f6);
	echo "$username:$user_id:$path";
done < $file
