#!/usr/bin/env bash
#Script to create a story depending on the contents of the /etc/passwd file
filename="/etc/passwd";
while read -r line
do
	username=$(echo "$line" | cut -d ":" -f1);
	password=$(echo "$line" | cut -d ":" -f2);
	user_id=$(echo "$line" | cut -d ":" -f3);
	group_id=$(echo "$line" | cut -d ":" -f4);
	user_info_id=$(echo "$line" | cut -d ":" -f5);
	home_dir=$(echo "$line" | cut -d ":" -f6);
	command=$(echo "$line" | cut -d ":" -f7);
	echo "The user $username is part of the $group_id gang, lives in $home_dir and rides $command. $user_id's place is protected by the passcode $password, more info about the user here: $user_info_id";
done < $filename
