#!/usr/bin/env bash
#Displays the number of occurences of the IP of the visitor along with the status code from the apache log file
awk '{print $1 " " $9}' apache-access.log | sort | uniq -c | sort -nr ;
