#!/usr/bin/env bash
#Script displays 10 sentences Best Shool or for 4th Bad luck, for 8th good luck
i=0;
while [ $i -lt 10 ]
do
	if [ "$i" -eq 3 ]
	then
		echo "bad luck";
	elif [ "$i" -eq 7 ]
	then
		echo "good luck";
	else
		echo "Best School";
	fi
	((i++));
done
