#!/usr/bin/env bash
#Displays the numbers from 1 to 20 and some sentences depending on the number
i=1;
while [ $i -le 20 ]
do
	echo $i;
	case "$i" in
		4) echo "bad luck from China"
		;;
		9) echo "bad luck from Japan"
		;;
		17) echo "bad luck from Italy"
		;;
	esac
	((i++));
done
